# Generated by Django 3.1.2 on 2020-10-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
