# Generated by Django 3.1.2 on 2020-10-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20201013_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='sex',
            new_name='Gender',
        ),
    ]
